### ISSUE TITLE
Storage encryption key length causes app to crash

### ISSUE THREAD

**Issue by ablease** [Peripli/service-manager#230]
# Problem
Deploying service-manager to CF is failing due to the length of STORAGE_ENCRYPTION_KEY

# Description
Output of cf logs service-manager --recent
```bash
   2019-02-13T16:07:44.33+0000 [CELL/0] OUT Starting health monitoring of container
   2019-02-13T16:07:44.48+0000 [APP/PROC/WEB/0] ERR time="2019-02-13T16:07:44Z" level=info msg="Config File was not found: Config File \"application\" Not Found in \"[/app]\""
   2019-02-13T16:07:44.48+0000 [APP/PROC/WEB/0] ERR time="2019-02-13T16:07:44Z" level=warning msg="No PostgreSQL service name found"
   2019-02-13T16:07:44.48+0000 [APP/PROC/WEB/0] ERR panic: error validating configuration: validate Settings: SecurityEncryptionkey length must be exactly 32
   2019-02-13T16:07:44.48+0000 [APP/PROC/WEB/0] ERR goroutine 1 [running]:
   2019-02-13T16:07:44.48+0000 [APP/PROC/WEB/0] ERR github.com/Peripli/service-manager/pkg/sm.New(0xa0cf20, 0xc4200688c0, 0xc42001d540, 0xa0d1a0, 0xc42000c0d8, 0x0)
   2019-02-13T16:07:44.48+0000 [APP/PROC/WEB/0] ERR 	/go/src/github.com/Peripli/service-manager/pkg/sm/sm.go:86 +0x786
   2019-02-13T16:07:44.48+0000 [APP/PROC/WEB/0] ERR main.main()
   2019-02-13T16:07:44.48+0000 [APP/PROC/WEB/0] ERR 	/go/src/github.com/Peripli/service-manager/main.go:30 +0xa7
   2019-02-13T16:07:44.53+0000 [APP/PROC/WEB/0] OUT Exit status 2
   2019-02-13T16:07:44.53+0000 [CELL/SSHD/0] OUT Exit status 0
   2019-02-13T16:07:44.84+0000 [CELL/0] OUT Cell 4c15ea70-9126-4f80-883d-5a2fa1b97bb3 stopping instance d397eb86-c5bb-45bd-58b2-e824
   2019-02-13T16:07:44.84+0000 [CELL/0] OUT Cell 4c15ea70-9126-4f80-883d-5a2fa1b97bb3 destroying container for instance d397eb86-c5bb-45bd-58b2-e824
   2019-02-13T16:07:44.85+0000 [API/0] OUT Process has crashed with type: "web"
   2019-02-13T16:07:44.86+0000 [API/0] OUT App instance exited with guid c0ac532d-cd60-4c72-b532-e514f6946ba5 payload: {"instance"=>"d397eb86-c5bb-45bd-58b2-e824", "index"=>0, "cell_id"=>"4c15ea70-9126-4f80-883d-5a2fa1b97bb3", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 2", "crash_count"=>3, "crash_timestamp"=>1550074064832171734, "version"=>"b712a98e-a1c6-4b42-9e8c-9d95de711281"}
   2019-02-13T16:07:45.21+0000 [CELL/0] OUT Cell 4c15ea70-9126-4f80-883d-5a2fa1b97bb3 successfully destroyed container for instance d397eb86-c5bb-45bd-58b2-e824
```

# To Reproduce

Follow the service-manager [docs](https://github.com/Peripli/service-manager/blob/master/docs/install/sm.md), deploy service manager to cf using `cf push -f deployment/cf/manifest.yml`. 
Here is my `deployment/cf/manifest.yml` 
```yaml
---
applications:
- name: service-manager
  memory: 64M
  docker:
    image: quay.io/service-manager/core:v0.1.1
  env:
    GOVERSION: go1.11
    GOPACKAGENAME: github.com/Peripli/service-manager
    LOG_FORMAT: json
    LOG_LEVEL: info
    API_TOKEN_ISSUER_URL: https://uaa.my-real-cf-instance.com
    API_CLIENT_ID: cf
    API_SKIP_SSL_VALIDATION: true
    STORAGE_ENCRYPTION_KEY: ejHjRNHbS0NaqARSRvnweVV9zcmhQEa8
    STORAGE_URI: postgres://my-postgres-instance-hosted-on-elephantsql.com
    STORAGE_SKIP_SSL_VALIDATION: true
```
Notice how I removed the `  services: <postgre_instance_name>`. I removed this since it was causing problems with `cf push`

To me it seems like the app panics due to, the length of an encryption key being incorrect. The encryption key in my manifest is 32 chars. 
```
panic: error validating configuration: validate Settings: SecurityEncryptionkey length must be exactly 32
```

Output of cf env
```bash
→ cf env service-manager
Getting env variables for app service-manager in org acceptance / space dev as admin...
OK

System-Provided:


{
 "VCAP_APPLICATION": {
  "application_id": "62df1a37-b5a2-440f-b624-b7e3cc4dac5c",
  "application_name": "service-manager",
  "application_uris": [
   "service-manager.wild-puma.sapi.cf-app.com"
  ],
  "application_version": "0dc3de48-0359-4b33-a9b6-1a2f56f63de3",
  "cf_api": "https://api.wild-puma.sapi.cf-app.com",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 64
  },
  "name": "service-manager",
  "space_id": "a4b32ab8-7b8f-4687-8ae6-a90cac72a080",
  "space_name": "dev",
  "uris": [
   "service-manager.wild-puma.sapi.cf-app.com"
  ],
  "users": null,
  "version": "0dc3de48-0359-4b33-a9b6-1a2f56f63de3"
 }
}

User-Provided:
API_CLIENT_ID: cf
API_SKIP_SSL_VALIDATION: true
API_TOKEN_ISSUER_URL: https://uaa.wild-puma.sapi.cf-app.com
GOPACKAGENAME: github.com/Peripli/service-manager
GOVERSION: go1.11
LOG_FORMAT: json
LOG_LEVEL: info
STORAGE_ENCRYPTION_KEY: ejHjRNHbS0NaqARSRvnweVV9zcmhQEa8
STORAGE_SKIP_SSL_VALIDATION: true
STORAGE_URI: postgres://sgotuioi:7jLcrqUve9dcrujZFT06pIpfPTsDm0FU@manny.db.elephantsql.com:5432/sgotuioi

No running env variables have been set

No staging env variables have been set
```
  
  
  [1]: https://github.com/Peripli
  [2]: service-manager-wg@googlegroups.com

**Comment by KirilKabakchiev** [comment]
Hi,

It looks like you are using a pretty old version. In it the environmwnt variable names are different for some configs (e.x. - its API_SECURITY_ENCRYPTION_KEY in the version you are using and this was later changed to STORAGE_. I would suggest switching to the latest release of all SM components as there are a lot of new stuff (services, plans, visibilities, labels, field and label querying/selectors(similar to k8s), etc

**Comment by ablease** [comment]
Hmm. I'm using the latest code on the master branch. Is master the current update branch?

Also I grepped for "API_SECURITY_ENCRYPTION_KEY" and it is nowhere in the codebase. I am using "STORAGE_ENCRYPTION_KEY" in my cf app manifest for service-manager.

**Comment by KirilKabakchiev** [comment]
I thought you are using 0.1.1 ? Atleast thats what you have written in the issue in the manifest.yml. I think we have 0.1.9 already in quay (for sm core that is)

**Comment by ablease** [comment]
Aha! That worked! I didn't think to check the docker image :)

I guess its a little confusing that docker image specified in the `deployments/cf/manifest.yml` for the v0.1.9 release references and image for an old release. 

I could PR a change to update the image so that it matches the current release.

**Comment by KirilKabakchiev** [comment]
Hi,

I agree that its confusing - hopefully we will eventually automate this version bump as part of the build. For the time being, proposing a PR to bump the version sounds great.
